bookstore/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^$', views.home),
    url(r'^login$', views.login, name='himanshu'),
    url(r'^register', views.register, name='shubham'),
    url(r'^homepage$', views.home, name='hemu'),
    url(r'^dota$', views.dota, name='dotame'),
    url(r'^copyright$', views.copyright, name='copy'),
    url(r'^donate$', views.donate, name='donate'),
    url(r'^shortstory$', views.shortstory, name='shortstory'),
    url(r'^novels$', views.novels, name='novels'),
    url(r'^art$', views.art, name='art'),
    url(r'^creative$', views.creative, name='creative'),
    url(r'^novels1$', views.novels1, name='novels1'),
    url(r'^art1$', views.art1, name='art1'),
    url(r'^creative1$', views.creative1, name='creative1'),
    url(r'^take$', views.take, name='take'),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^add$', views.add, name='add'),
    url(r'^view$', views.view, name='view'),
    url(r'^logout$', auth_views.logout, {'template_name': 'bookstore/logout.html'}, name='logout'),

]

collegeproj/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^bookstore/', include('bookstore.urls', namespace='homeurl')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookstore/models.py
from django.db import models


# Create your models here.

class Regis_db(models.Model):
    name = models.CharField(max_length=25)
    emailid = models.CharField(max_length=25)
    password = models.CharField(max_length=25)
    confirm_password = models.CharField(max_length=25)

    def __str__(self):
        return self.name


class donate_db(models.Model):
    Category = models.CharField(max_length=25)
    Book_Name = models.CharField(max_length=40)
    Author_Name = models.CharField(max_length=25)
    Donater_name = models.CharField(max_length=25)
    Mob_no = models.IntegerField(max_length=25)
    Email_id = models.CharField(max_length=25)
    Select_State = models.CharField(max_length=25)
    City_name = models.CharField(max_length=25)
    filename = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.Donater_name


class contact_db(models.Model):
    Your_name = models.CharField(max_length=25)
    Email_Address = models.CharField(max_length=25)
    Mobile_No = models.CharField(max_length=25)
    Message = models.CharField(max_length=250)

    def __str__(self):
        return self.Your_name

bookstore/views.py
from django.contrib import auth
from django.contrib import messages
from django.shortcuts import render, redirect

from .models import Regis_db, donate_db, contact_db


def home(request):
    return render(request, 'bookstore/home.html')


def login(request):
    if 'em' in request.session:
        em = request.session['em']
        return redirect('homeurl:dotame')
    elif request.method == 'POST':
        em = request.POST.get('emailid')
        pa = request.POST.get('password')

        if (len(Regis_db.objects.filter(emailid=em)) and
                len(Regis_db.objects.filter(password=pa))):
            request.session['em'] = em
            return redirect('homeurl:dotame')
    return render(request, 'bookstore/login.html')


def register(request):
    if request.method == "POST":
        name = request.POST['username']
        emailid = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        reg_db_obj = Regis_db()
        reg_db_obj.name = name
        reg_db_obj.emailid = emailid
        reg_db_obj.password = password

        reg_db_obj.confirm_password = confirm_password
        reg_db_obj.save()
        return redirect('homeurl:himanshu')

    return render(request, 'bookstore/register.html')


def hemu(request):
    return render(request, 'bookstore/home.html')


def dota(request):
    # # em = None
    # if (request.method == "GET"):
    #     if 'action' in request.GET:
    #         action = request.GET.get('action')
    #         if action == 'logout':
    #             if request.session.has_key('em'):
    #                 request.session.flush()
    #                 return redirect('homeurl:himanshu')
    # if 'em' in request.session:
    #     em= request.session['em']
    return render(request, 'bookstore/dota.html')


def copyright(request):
    return render(request, 'bookstore/copyright.html')


def donate(request):
    if request.method == "POST":
        Category = request.POST['Category']
        Book_Name = request.POST['Book_Name']
        Author_Name = request.POST['Author_Name']
        Donater_name = request.POST['Donater_name']
        Mob_no = request.POST['Mob_No']
        Email_id = request.POST['Email_id']
        City_name = request.POST['City_name']
        Select_State = request.POST['Select_State']

        reg_db_obj = donate_db(filename=request.FILES['filename'])

        reg_db_obj.Category = Category
        reg_db_obj.Book_Name = Book_Name
        reg_db_obj.Donater_name = Donater_name
        reg_db_obj.Mob_no = Mob_no
        reg_db_obj.Email_id = Email_id
        reg_db_obj.Author_Name = Author_Name
        reg_db_obj.City_name = City_name
        reg_db_obj.Select_State = Select_State

        reg_db_obj.save()
        messages.success(request, 'saved')
        print(1)
        return redirect('homeurl:add')

    return render(request, 'bookstore/donate.html')


def shortstory(request):
    return render(request, 'bookstore/shortstory.html')


def novels(request):
    return render(request, 'bookstore/novels.html')


def art(request):
    return render(request, 'bookstore/art.html')


def creative(request):
    return render(request, 'bookstore/creative.html')


def novels1(request):
    return render(request, 'bookstore/novels1.html')


def art1(request):
    return render(request, 'bookstore/art1.html')


def creative1(request):
    return render(request, 'bookstore/creative1.html')


def take(request):
    obj = donate_db.objects.all()

    return render(request, 'bookstore/take.html',
                  {'data': obj})


def contact(request):
    if request.method == "POST":
        Your_name = request.POST['Your_name']
        Email_Address = request.POST['Email_Address']
        Mobile_No = request.POST['Mobile_No']
        Message = request.POST['Message']

        reg_db_obj = contact_db()
        reg_db_obj.Your_name = Your_name
        reg_db_obj.Email_Address = Email_Address
        reg_db_obj.Mobile_No = Mobile_No
        reg_db_obj.Message = Message

        reg_db_obj.save()
        return redirect('homeurl:hemu')

    return render(request, 'bookstore/contact.html')


def logout(request):
    auth.logout(request)
    return render(request, 'bookstore/logout.html')


def add(request):
    return render(request, 'bookstore/add.html')


def view(request):
    return render(request, 'bookstore/view.html')

bookstore/templates/bookstore/add.html
<style xmlns="http://www.w3.org/1999/html">
            body {
                background: linear-gradient(132deg, #f44336, #E91E63, #9C27B0, #673AB7, #3F51B5, #2196F3,#03A9F4, #00BCD4, #009688, #4CAF50, #FFC107, #FF9800, #f44336, #E91E63, #9C27B0, #673AB7, #3F51B5, #2196F3,#03A9F4, #00BCD4, #009688, #4CAF50, #FFC107, #FF9800);
                background-size: 400% 400%;
                animation: BackgroundGradient 30s ease infinite;
            }

            @keyframes BackgroundGradient {
                0% {background-position: 0% 50%;}
                50% {background-position: 100% 50%;}
                100% {background-position: 0% 50%;}
            }
            .baslik
{
    color: #fff;
    text-align: center;
    font-family: 'Fira Sans', sans-serif;
}
.arkalogin
{
    width: 300px;
    text-align: center;
    background: #fff;
    height: 300px;
    padding: 10px;
    margin: 50px auto;
}
.loginbaslik
{
    color: #888888;
    text-align: left;
    font-size: 19px;
    margin-top: 15px;
}
.giris
{
    width: 100%;
    height: 40px;
    margin-top: 10px;
    border: none;
    background: #E5E5E5;
    outline: none;
    padding: 0 10px;
}
.butonlogin
{
    width: 100%;
    margin-top: 10px;
    height: 40px;
    font-weight: bold;
    background: #2196F3;
    border: none;
    color: #fff;
    transition: all 250ms;
}
.butonlogin:hover
{
    background: #1E88E5;
}
body
{
    margin: 0;
}

</style>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<section style="height: 100vh;">
    <div style="background-image: url(images/arka.jpg); background-attachment: fixed; background-size: cover; width: 100%; height: 100vh; position: relative;">
        <div class="baslik">
            <b style="font-size: 101px; text-align: center; margin-bottom: -21px; display: block;">BOOKSTORE</b>
            <span style="font-size: 19px; text-align: center; display: block; margin-bottom: 25px;">DONATION STATUS</span>
        </div>
        <section>
            <form method="" action="">
                <div class="arkalogin">
                    <div class="loginbaslik">Ad poted succesfully</div>
                    <hr style="border: 1px solid #ccc;">
                    <input class="butonlogin" type="submit" name="" value="view your add">
                    <input class="butonlogin" type="submit" name="" value="submit another ad">
                    <a class="btn btn-primary " href="{% url 'homeurl:donate'%}"></a>
                </div>
            </form>
        </section>
        <br>

    </div>
</section>

bookstore/templates/bookstore/art.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bookstore/shortstory.css' %}"/>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>short story</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'homeurl:hemu'%}">
        {% load static %}
        <img src="{% static 'bookstore/images/hicon.png' %}" width="30" height="30" class="d-inline-block align-top"
             alt="">
        Home
    </a>
</nav>
<div class="container" style="background-color:lightgray;height:600px;width:900px;">
    <h4>Art of the Short Story</h4>


    <div class="row">
        <div class="col-sm-4">
            <img src="{% static 'bookstore/images//novels/teeth.jpg' %}" alt="A image"
                 style="height:100px;width:150px;"/>
            <br>
            <a href="{% url 'homeurl:art1'%}" class="btn btn-two">teeth of december</a>

        </div>
        <div class="col-sm-4">
            <img src="{% static 'bookstore/images//novels/index2.jpg' %}" alt="A image"
                 style="height:100px;width:150px;"/>
            <br>
            <a href="{% url 'homeurl:art1'%}" class="btn btn-two">Dubliner</a>

        </div>
        <div class="col-sm-4">
            <img src="{% static 'bookstore/images//novels/index3.png' %}" alt="A image"
                 style="height:100px;width:150px;"/>
            <br>
            <a href="{% url 'homeurl:art1'%}" class="btn btn-two">This is how you lose her</a>

        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <img src="{% static 'bookstore/images/novels/index4.jpg' %}" alt="A image"
                         style="height:100px;width:150px;"/>
                    <br>
                    <a href="{% url 'homeurl:art1'%}" class="btn btn-two">Interpreter of maladies</a>
                </div>
                <div class="col-sm-4">
                    <img src="{% static 'bookstore/images/novels/index5.jpg' %}" alt="A image"
                         style="height:100px;width:150px;"/>
                    <br>
                    <a href="{% url 'homeurl:art1'%}" class="btn btn-two">Different Seasons</a>
                </div>
                <div class="col-sm-4">
                    <img src="{% static 'bookstore/images/novels/before.jpg' %}" alt="A image"
                         style="height:100px;width:150px;"/>
                    <br>
                    <a href="{% url 'homeurl:art1'%}" class="btn btn-two">To all the boy i've</a>


                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-sm-4">
                            <img src="{% static 'bookstore/images/novels/index6.jpg' %}" alt="A image"
                                 style="height:100px;width:150px;"/>
                            <br>
                            <a href="{% url 'homeurl:art1'%}" class="btn btn-two">Fragile Thin</a>
                        </div>
                        <div class="col-sm-4">
                            <img src="{% static 'bookstore/images/novels/rules.jpg' %}" alt="A image"
                                 style="height:100px;width:150px;"/>
                            <br>
                            <a href="{% url 'homeurl:art1'%}" class="btn btn-two">Beautiful broken rules</a>
                        </div>
                        <div class="col-sm-4">
                            <img src="{% static 'bookstore/images/novels/index7.jpg' %}" alt="A image"
                                 style="height:100px;width:150px;"/>
                            <br>
                            <a href="{% url 'homeurl:art1'%}" class="btn btn-two">Your life</a>


                        </div>
                        <div class="container">
                            <div class="row">
                                <div class="col-sm-4">
                                    <img src="{% static 'bookstore/images/novels/index7.jpg' %}" alt="A image"
                                         style="height:100px;width:150px;"/>
                                    <br>
                                    <a href="{% url 'homeurl:art1'%}" class="btn btn-two">The Bazar of bad dreams</a>
                                </div>
                                <div class="col-sm-4">
                                    <img src="{% static 'bookstore/images/novels/index9.jpg' %}"
                                         alt="A image"
                                         style="height:100px;width:150px;"/>
                                    <br>
                                    <a href="{% url 'homeurl:art1'%}" class="btn btn-two">The Dead</a>
                                </div>
                                <div class="col-sm-4">
                                    <img src="{% static 'bookstore/images/novels/images1.jpg' %}" alt="A image"
                                         style="height:100px;width:150px;"/>
                                    <br>
                                    <a href="{% url 'homeurl:art1'%}" class="btn btn-two">The YEllow wallpaper</a>


                                </div>
                            </div>


</body>
</html>

bookstore/templates/bookstore/dota.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css"
      xmlns="http://www.w3.org/1999/html">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>DONATE & TAKE</title>
    <link rel="stylesheet" href="https://headervideo.github.io/hvheadervideo/css/fontawesome.min.css">
    <link href="https://headervideo.github.io/hvheadervideo/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://headervideo.github.io/hvheadervideo/css/mdb.min.css" rel="stylesheet">
    <link href="https://headervideo.github.io/hvheadervideo/css/style.css" rel="stylesheet">
</head>
<body>
<!--Main Navigation-->
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'homeurl:logout' %}">LOGOUT</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse " id="navbarSupportedContent">


        </div>
    </nav>
</header>

<div class="view hm-white-light jarallax" data-jarallax='{"speed": 5.2}'

     data-jarallax-video="https://www.youtube.com/watch?v=SKVcQnyEIT8">

    <div class="full-bg-img">
        <div class="container flex-center">
            <div class="row">
                <div class="col-md-12 wow fadeIn">
                    <div class="text-center text-danger">
                        <h1 class="display-2 mb-2 wow fadeInDown" data-wow-delay="0.3s">DONATE BOOK&TAKE AWAY</h1>
                        <h5 class="font-up mb-3 mt-1 font-bold wow fadeInDown" data-wow-delay="0.4s">First Website
                            In Which <br>You can <b>Donate Your Book</b> <b>And TAke Away Free</b>
                        </h5>
                        <a class="btn btn-danger btn-lg wow fadeInDown" data-wow-delay="0.4s"
                           href="{% url 'homeurl:donate'%}"> book donate</a>
                        <a class="btn btn-primary btn-lg wow fadeInDown" data-wow-delay="0.4s"
                           href="{% url 'homeurl:take'%}"> take away</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</div>


</div>

</div>
</div>
</div>

<script type="text/javascript" src="https://headervideo.github.io/hvheadervideo/js/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="https://headervideo.github.io/hvheadervideo/js/popper.min.js"></script>
<script src="https://headervideo.github.io/hvheadervideo/js/bootstrap.min.js"></script>
<script src="https://headervideo.github.io/hvheadervideo/js/mdb.min.js"></script>
<script src="https://headervideo.github.io/hvheadervideo/js/jarallax.js"></script>
<script src="https://headervideo.github.io/hvheadervideo/js/jarallax-video.js"></script>
<script>
       new WOW().init();





</script>
</body>
</html>
<!--&lt;!&ndash;{% load static %}&ndash;&gt;-->
<!--<link rel="stylesheet" type="text/css" href="{% static 'bookstore/dota.css' %}"/>-->
<!--<!DOCTYPE html>-->


<!--<html lang="en">-->
<!--<head>-->
<!--<meta charset="UTF-8">-->
<!--<title>dota</title>-->
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">-->

<!--&lt;!&ndash; jQuery library &ndash;&gt;-->
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.0/jquery.min.js"></script>-->

<!--&lt;!&ndash; Popper JS &ndash;&gt;-->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>-->

<!--&lt;!&ndash; Latest compiled JavaScript &ndash;&gt;-->
<!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/1.11.1/js/bootstrap.min.js"></script>-->
<!--</head>-->
<!--<body>-->
<!--<nav class="navbar navbar-light bg-light">-->
<!--<a class="navbar-brand" href="{% url 'homeurl:logout' %}">-->

<!--Logout-->
<!--</a>-->
<!--</nav>-->
<!--<div class="container">-->
<!--<a href="{% url 'homeurl:donate'%}" class="btn btn-1">DONATE BOOK</a>-->
<!--<a href="{% url 'homeurl:take'%}" class="btn btn-2">TAKE AWAY</a>-->
<!--</div>-->
<!--&lt;!&ndash;<nav class="navbar navbar-light bg-light">&ndash;&gt;-->
<!--&lt;!&ndash;<a class="navbar-brand" href="{% url 'homeurl:logout' %}">&ndash;&gt;-->

<!--&lt;!&ndash;Logout&ndash;&gt;-->
<!--&lt;!&ndash;</a>&ndash;&gt;-->
<!--&lt;!&ndash;</nav>&ndash;&gt;-->
<!--&lt;!&ndash;<div class="row">&ndash;&gt;-->
<!--&lt;!&ndash;<div class="col-sm-6">&ndash;&gt;-->
<!--&lt;!&ndash;<div class="card">&ndash;&gt;-->
<!--&lt;!&ndash;<div class="card-body">&ndash;&gt;-->
<!--&lt;!&ndash;<h5 class="card-title">Special title treatment</h5>&ndash;&gt;-->
<!--&lt;!&ndash;<p class="card-text">With supporting text below as a natural lead-in to additional content.</p>&ndash;&gt;-->
<!--&lt;!&ndash;<a href="{% url 'homeurl:donate'%}" class="btn btn-primary">Donate Book</a>&ndash;&gt;-->
<!--&lt;!&ndash;</div>&ndash;&gt;-->
<!--&lt;!&ndash;</div>&ndash;&gt;-->
<!--&lt;!&ndash;</div>&ndash;&gt;-->
<!--&lt;!&ndash;<div class="col-sm-6">&ndash;&gt;-->
<!--&lt;!&ndash;<div class="card">&ndash;&gt;-->
<!--&lt;!&ndash;<div class="card-body">&ndash;&gt;-->
<!--&lt;!&ndash;<h5 class="card-title">Special title treatment</h5>&ndash;&gt;-->
<!--&lt;!&ndash;<p class="card-text">With supporting text below as a natural lead-in to additional content.</p>&ndash;&gt;-->
<!--&lt;!&ndash;<a href="{% url 'homeurl:take'%}" class="btn btn-primary"> Take Away </a>&ndash;&gt;-->
<!--&lt;!&ndash;</div>&ndash;&gt;-->
<!--&lt;!&ndash;</div>&ndash;&gt;-->
<!--&lt;!&ndash;</div>&ndash;&gt;-->
<!--&lt;!&ndash;</div>&ndash;&gt;-->
<!--&lt;!&ndash;<br>&ndash;&gt;-->


<!--</body>-->
<!--&lt;!&ndash;</html>&ndash;&gt;-->

bookstore/templates/bookstore/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="content">
    <div class="">
        <p> You Are logged out. <a href="{% url 'homeurl:himanshu' %}">click here</a>to login again</p>
    </div>
</div>

</body>
</html>

bookstore/templates/bookstore/shortstory.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bookstore/shortstory.css' %}"/>

<head>
    <meta charset="UTF-8">
    <title>short story</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'homeurl:hemu'%}">
        {% load static %}
        <img src="{% static 'bookstore/images/hicon.png' %}" width="30" height="30" class="d-inline-block align-top"
             alt="">
        Home
    </a>
</nav>
<div class="container" style="background-color:lightgray;height:600px;width:900px;">
    <h4>NOVELS</h4>


    <div class="row">
        <div class="col-sm-4">
            <img src="{% static 'bookstore/images//novels/park.jpg' %}" alt="A image"
                 style="height:100px;width:150px;"/>
            <br>
            <a href="{% url 'homeurl:novels'%}" class="btn btn-two">Eleanor & Park</a>

        </div>
        <div class="col-sm-4">
            <img src="{% static 'bookstore/images//novels/fangirl.jpg' %}" alt="A image"
                 style="height:100px;width:150px;"/>
            <br>
            <a href="{% url 'homeurl:novels1'%}" class="btn btn-two">FANGIRL</a>

        </div>
        <div class="col-sm-4">
            <img src="{% static 'bookstore/images//novels/origin.jpg' %}" alt="A image"
                 style="height:100px;width:150px;"/>
            <br>
            <a href="{% url 'homeurl:novels1'%}" class="btn btn-two">ORIGIN</a>

        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <img src="{% static 'bookstore/images/novels/boyfriend.jpg' %}" alt="A image"
                         style="height:100px;width:150px;"/>
                    <br>
                    <a href="{% url 'homeurl:novels1'%}" class="btn btn-two">fill in boyfriend</a>
                </div>
                <div class="col-sm-4">
                    <img src="{% static 'bookstore/images/novels/fence.jpg' %}" alt="A image"
                         style="height:100px;width:150px;"/>
                    <br>
                    <a href="{% url 'homeurl:novels1'%}" class="btn btn-two">On the fence</a>
                </div>
                <div class="col-sm-4">
                    <img src="{% static 'bookstore/images/novels/before.jpg' %}" alt="A image"
                         style="height:100px;width:150px;"/>
                    <br>
                    <a href="{% url 'homeurl:novels1'%}" class="btn btn-two">To all the boy i've</a>


                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-sm-4">
                            <img src="{% static 'bookstore/images/novels/pretty.jpg' %}" alt="A image"
                                 style="height:100px;width:150px;"/>
                            <br>
                            <a href="{% url 'homeurl:novels1'%}" class="btn btn-two">The summer i turned</a>
                        </div>
                        <div class="col-sm-4">
                            <img src="{% static 'bookstore/images/novels/rules.jpg' %}" alt="A image"
                                 style="height:100px;width:150px;"/>
                            <br>
                            <a href="{% url 'homeurl:novels1'%}" class="btn btn-two">Beautiful broken rules</a>
                        </div>
                        <div class="col-sm-4">
                            <img src="{% static 'bookstore/images/novels/index.jpg' %}" alt="A image"
                                 style="height:100px;width:150px;"/>
                            <br>
                            <a href="{% url 'homeurl:novels1'%}" class="btn btn-two">The great indian novel</a>


                        </div>
                        <div class="container">
                            <div class="row">
                                <div class="col-sm-4">
                                    <img src="{% static 'bookstore/images/novels/god.jpg' %}" alt="A image"
                                         style="height:100px;width:150px;"/>
                                    <br>
                                    <a href="{% url 'homeurl:novels1'%}" class="btn btn-two">The god of small things</a>
                                </div>
                                <div class="col-sm-4">
                                    <img src="{% static 'bookstore/images/novels/tiger.png' %}"
                                         alt="A image"
                                         style="height:100px;width:150px;"/>
                                    <br>
                                    <a href="{% url 'homeurl:novels1'%}" class="btn btn-two">The white tiger</a>
                                </div>
                                <div class="col-sm-4">
                                    <img src="{% static 'bookstore/images/novels/boy.jpg' %}" alt="A image"
                                         style="height:100px;width:150px;"/>
                                    <br>
                                    <a href="{% url 'homeurl:novels1'%}" class="btn btn-two">The suitable boy</a>


                                </div>
                            </div>

</body>
</html>